# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my-autograd',
                'doc_host': 'https://LawJarp-A.github.io',
                'git_url': 'https://github.com/LawJarp-A/my-autograd',
                'lib_path': 'my_autograd'},
  'syms': {'my_autograd.core': {'my_autograd.core.foo': ('core.html#foo', 'my_autograd/core.py')}}}
