name: CI

on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python and Install Graphviz
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Adjust the Python version as needed

    - name: Install Graphviz
      run: |
        sudo apt-get update
        sudo apt-get install graphviz

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run tests
      uses: fastai/workflows/nbdev-ci@master
